<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example.dataproducts</groupId>
    <artifactId>data-products-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>data-products/orders</module>
        <module>data-products/customers</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.build.outputTimestamp>2026-01-01T00:00:00Z</project.build.outputTimestamp>
        <maven.assembly.version>3.8.0</maven.assembly.version>
    </properties>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven.assembly.version}</version>
                    <configuration>
                        <descriptors>
                            <descriptor>${maven.multiModuleProjectDirectory}/scripts/assembly/data-product.xml</descriptor>
                        </descriptors>
                        <finalName>${project.artifactId}-${product.release.version}</finalName>
                        <appendAssemblyId>false</appendAssemblyId>
                        <outputTimestamp>${project.build.outputTimestamp}</outputTimestamp>
                    </configuration>
                    <executions>
                        <execution>
                            <id>assemble-data-product</id>
                            <phase>package</phase>
                            <goals>
                                <goal>single</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
